[workspace]

[package]
name = "ensure_no_std"
version = "0.1.0"
edition = "2021"

[dependencies]
ros_pointcloud2 = { path = "..", default-features = false, features = ["nalgebra", "derive"] }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
