name: Tests

on:
  push:
    branches-ignore:
      - rclrs
  pull_request:
    branches-ignore:
      - rclrs
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv7em-none-eabihf
      - name: no_std build
        run: cargo build --target thumbv7em-none-eabihf --manifest-path rpcl2/ensure_no_std/Cargo.toml
