name: r2r_galactic

on:
  push:
    branches:
      - "*"
      - "!rclrs"
  pull_request:
    branches:
      - "*"
      - "!rclrs"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests_galactic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build . --file ./tests/Dockerfile_r2r_galactic --tag r2r_galactic
    - run: docker run r2r_galactic cargo test --features r2r_msg
